name: local_skill_share
description: A new Flutter project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Networking
  dio: ^5.4.0

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0

  # Local DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Routing
  go_router: ^14.0.0

  # Maps & Location
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.0

  # Payments
  flutter_stripe: ^11.0.0

  # Utils
  uuid: ^4.3.3
  intl: ^0.19.0
  flutter_dotenv: ^5.0.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
